In [29]:
import pandas as pd

In [30]:
df=pd.read_csv('movies.csv')

In [31]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [32]:
# Checking for missing values in the entire dataset
print(df.isnull().sum())

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [33]:
print(df[df.isnull().any(axis=1)])

      index     budget                                     genres  \
10       10  270000000   Adventure Fantasy Action Science Fiction
15       15  225000000                   Adventure Family Fantasy
24       24  207000000                     Adventure Drama Action
27       27  209000000  Thriller Action Adventure Science Fiction
33       33  210000000  Adventure Action Science Fiction Thriller
...     ...        ...                                        ...
4798   4798     220000                      Action Crime Thriller
4799   4799       9000                             Comedy Romance
4800   4800          0              Comedy Drama Romance TV Movie
4801   4801          0                                        NaN
4802   4802          0                                Documentary

                                               homepage      id  \
10                              http://www.superman.com    1452
15                                                  NaN    2454
24                                                  NaN     254
27                                                  NaN   44833
33                                                  NaN   36668
...                                                 ...     ...
4798                                                NaN    9367
4799                                                NaN   72766
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617
4801                        http://shanghaicalling.com/  126186
4802                                                NaN   25975

                                               keywords original_language  \
10    saving the world dc comics invulnerability seq...                en
15    based on novel fictional place brother sister ...                en
24    film business screenplay show business film ma...                en
27        fight u.s. navy mind reading hong kong soccer                en
33    mutant marvel comic based on comic book superh...                en
...                                                 ...               ...
4798  united states\u2013mexico barrier legs arms pa...                es
4799                                                NaN                en
4800  date love at first sight narration investigati...                en
4801                                                NaN                en
4802               obsession camcorder crush dream girl                en

                                original_title  \
10                            Superman Returns
15    The Chronicles of Narnia: Prince Caspian
24                                   King Kong
27                                  Battleship
33                       X-Men: The Last Stand
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  ...  \
10    Superman returns to discover his 5-year absenc...   57.925623  ...
15    One year after their incredible adventures in ...   53.978602  ...
24    In 1933 New York, an overly ambitious movie pr...   61.226010  ...
27    When mankind beams a radio signal into space, ...   64.928382  ...
33    When a cure is found to treat mutations, lines...    3.857526  ...
...                                                 ...         ...  ...
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...
4802  Ever since the second grade when he first saw ...    1.929883  ...

     runtime                                   spoken_languages    status  \
10     154.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
15     150.0           [{"iso_639_1": "en", "name": "English"}]  Released
24     187.0           [{"iso_639_1": "en", "name": "English"}]  Released
27     131.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
33     104.0           [{"iso_639_1": "en", "name": "English"}]  Released
...      ...                                                ...       ...
4798    81.0      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799    85.0                                                 []  Released
4800   120.0           [{"iso_639_1": "en", "name": "English"}]  Released
4801    98.0           [{"iso_639_1": "en", "name": "English"}]  Released
4802    90.0           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
10                                                  NaN
15                                 Hope has a new face.
24                      The eighth wonder of the world.
27                   The Battle for Earth Begins at Sea
33                                         Take a Stand
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                         title vote_average vote_count  \
10                            Superman Returns          5.4       1400
15    The Chronicles of Narnia: Prince Caspian          6.3       1630
24                                   King Kong          6.6       2337
27                                  Battleship          5.5       2114
33                       X-Men: The Last Stand          6.3       3525
...                                        ...          ...        ...
4798                               El Mariachi          6.6        238
4799                                 Newlyweds          5.9          5
4800                 Signed, Sealed, Delivered          7.0          6
4801                          Shanghai Calling          5.7          7
4802                         My Date with Drew          6.3         16

                                                   cast  \
10    Brandon Routh Kevin Spacey Kate Bosworth James...
15    Ben Barnes William Moseley Anna Popplewell Ska...
24    Naomi Watts Jack Black Adrien Brody Thomas Kre...
27    Taylor Kitsch Alexander Skarsg\u00e5rd Rihanna...
33    Hugh Jackman Halle Berry Ian McKellen Patrick ...
...                                                 ...
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...

                                                   crew          director
10    [{'name': 'Roger Mussenden', 'gender': 2, 'dep...      Bryan Singer
15    [{'name': 'Liz Mullane', 'gender': 1, 'departm...    Andrew Adamson
24    [{'name': 'James Newton Howard', 'gender': 2, ...     Peter Jackson
27    [{'name': 'Paul Rubell', 'gender': 2, 'departm...        Peter Berg
33    [{'name': 'Mark Goldblatt', 'gender': 2, 'depa...      Brett Ratner
...                                                 ...               ...
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...  Robert Rodriguez
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...      Edward Burns
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...       Scott Smith
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...       Daniel Hsia
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...  Brian Herzlinger

[3371 rows x 24 columns]

In [34]:
# Filling important columns' NaN values with an empty string
df['genres'] = df['genres'].fillna('')
df['keywords'] = df['keywords'].fillna('')
df['cast'] = df['cast'].fillna('')
df['director'] = df['director'].fillna('')
df['overview'] = df['overview'].fillna('')
df['tagline'] = df['tagline'].fillna('')

In [35]:
print(df.isnull().sum())

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   0
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [36]:
# Combine important features into a single column
df['combined_features'] = df['genres'] + ' ' + df['keywords'] + ' ' + df['cast'] + ' ' + df['director']

In [37]:
# Display the combined features for validation
df['combined_features'].head()

0    Action Adventure Fantasy Science Fiction cultu...
1    Adventure Fantasy Action ocean drug abuse exot...
2    Action Adventure Crime spy based on novel secr...
3    Action Crime Drama Thriller dc comics crime fi...
4    Action Adventure Science Fiction based on nove...
Name: combined_features, dtype: object

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

# Create a CountVectorizer object
cv = CountVectorizer(stop_words='english')

In [39]:
# Convert combined features to a matrix of token counts
count_matrix = cv.fit_transform(df['combined_features'])
from sklearn.metrics.pairwise import cosine_similarity
# Compute the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix)

In [40]:
# Display the similarity matrix shape
print(cosine_sim.shape)

(4803, 4803)

In [41]:
# Function to get the index of a movie from its title
def get_index_from_title(title):
    return df[df['title'] == title].index[0]

# Function to get the title of a movie from its index
def get_title_from_index(index):
    return df.iloc[index]['title']

In [42]:
# Function to recommend movies
def recommend_movies(movie_title, num_recommendations=10):
    movie_index = get_index_from_title(movie_title)
    similarity_scores = list(enumerate(cosine_sim[movie_index]))
    sorted_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    # Get top recommendations
    recommended_movie_indices = [x[0] for x in sorted_scores[1:num_recommendations+1]]
    return [get_title_from_index(idx) for idx in recommended_movie_indices]

In [43]:
# Testing
movie_name = "The Dark Knight"  
recommended_movies = recommend_movies(movie_name)

print(f"Movies similar to '{movie_name}':")
for i, movie in enumerate(recommended_movies, 1):
    print(f"{i}. {movie}")

Movies similar to 'The Dark Knight':
1. The Dark Knight Rises
2. Batman Begins
3. Amidst the Devil's Wings
4. The Prestige
5. Kick-Ass
6. Kick-Ass 2
7. Batman Returns
8. Batman
9. The Killer Inside Me
10. Batman & Robin